import pandas as pd

configfile: "config.yaml"

input_table = config["metadata"]["recount3"]
IDs = pd.read_csv(input_table).loc[:,"id"].tolist()

datasource = list(config["metadata"].keys())
print(datasource)


rule all:
    input:
        expand("../data/preProcess/{ids}.rds", ids=IDs, ds=datasource)

rule download:
    resources: 
        tmpdir="/scratch/tmp"
    params:
        id=IDs
    log:
        "logs/download/{id}.txt"
    input:
        metadata=config["metadata"]["recount3"]
    output:
        "Rdatas/{id}.rds"
    script:
        "scripts/downloadRecount3.R"

rule preProcess:
    resources: 
        tmpdir="/scratch/tmp"
    params:
        id=IDs,
        assay_name="raw_counts"
    log:
        "logs/preProcess/{id}.txt"
    input:
        data="Rdatas/{id}.rds", 
        metadata=config["metadata"]["recount3"]
    output:
        "../data/preProcess/{id}.rds"
    script:
        "scripts/preProcess.R"